input=$1

java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output1.out -c 0 0 0 0 0 $input > results_CR1.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output2.out -c 0 0 0 1 0 $input > results_CR2.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output3.out -c 0 0 0 2 0 $input > results_CR3.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output4.out -c 0 0 0 3 0 $input > results_CR4.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output5.out -c 0 0 1 0 0 $input > results_CR5.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output6.out -c 0 0 1 1 0 $input > results_CR6.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output7.out -c 0 0 1 2 0 $input > results_CR7.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output8.out -c 0 0 1 3 0 $input > results_CR8.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output9.out -c 0 0 2 0 0 $input > results_CR9.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output10.out -c 0 0 2 1 0 $input > results_CR10.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output11.out -c 0 0 2 2 0 $input > results_CR11.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output12.out -c 0 0 2 3 0 $input > results_CR12.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output13.out -c 0 0 3 0 0 $input > results_CR13.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output14.out -c 0 0 3 1 0 $input > results_CR14.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output15.out -c 0 0 3 2 0 $input > results_CR15.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output16.out -c 0 0 3 3 0 $input > results_CR16.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output17.out -c 0 1 0 0 0 $input > results_CR17.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output18.out -c 0 1 0 1 0 $input > results_CR18.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output19.out -c 0 1 0 2 0 $input > results_CR19.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output20.out -c 0 1 0 3 0 $input > results_CR20.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output21.out -c 0 1 1 0 0 $input > results_CR21.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output22.out -c 0 1 1 1 0 $input > results_CR22.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output23.out -c 0 1 1 2 0 $input > results_CR23.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output24.out -c 0 1 1 3 0 $input > results_CR24.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output25.out -c 0 1 2 0 0 $input > results_CR25.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output26.out -c 0 1 2 1 0 $input > results_CR26.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output27.out -c 0 1 2 2 0 $input > results_CR27.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output28.out -c 0 1 2 3 0 $input > results_CR28.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output29.out -c 0 1 3 0 0 $input > results_CR29.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output30.out -c 0 1 3 1 0 $input > results_CR30.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output31.out -c 0 1 3 2 0 $input > results_CR31.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output32.out -c 0 1 3 3 0 $input > results_CR32.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output33.out -c 0 2 0 0 0 $input > results_CR33.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output34.out -c 0 2 0 1 0 $input > results_CR34.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output35.out -c 0 2 0 2 0 $input > results_CR35.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output36.out -c 0 2 0 3 0 $input > results_CR36.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output37.out -c 0 2 1 0 0 $input > results_CR37.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output38.out -c 0 2 1 1 0 $input > results_CR38.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output39.out -c 0 2 1 2 0 $input > results_CR39.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output40.out -c 0 2 1 3 0 $input > results_CR40.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output41.out -c 0 2 2 0 0 $input > results_CR41.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output42.out -c 0 2 2 1 0 $input > results_CR42.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output43.out -c 0 2 2 2 0 $input > results_CR43.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output44.out -c 0 2 2 3 0 $input > results_CR44.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output45.out -c 0 2 3 0 0 $input > results_CR45.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output46.out -c 0 2 3 1 0 $input > results_CR46.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output47.out -c 0 2 3 2 0 $input > results_CR47.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output48.out -c 0 2 3 3 0 $input > results_CR48.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output49.out -c 0 3 0 0 0 $input > results_CR49.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output50.out -c 0 3 0 1 0 $input > results_CR50.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output51.out -c 0 3 0 2 0 $input > results_CR51.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output52.out -c 0 3 0 3 0 $input > results_CR52.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output53.out -c 0 3 1 0 0 $input > results_CR53.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output54.out -c 0 3 1 1 0 $input > results_CR54.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output55.out -c 0 3 1 2 0 $input > results_CR55.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output56.out -c 0 3 1 3 0 $input > results_CR56.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output57.out -c 0 3 2 0 0 $input > results_CR57.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output58.out -c 0 3 2 1 0 $input > results_CR58.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output59.out -c 0 3 2 2 0 $input > results_CR59.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output60.out -c 0 3 2 3 0 $input > results_CR60.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output61.out -c 0 3 3 0 0 $input > results_CR61.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output62.out -c 0 3 3 1 0 $input > results_CR62.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output63.out -c 0 3 3 2 0 $input > results_CR63.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output64.out -c 0 3 3 3 0 $input > results_CR64.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output65.out -c 1 0 0 0 0 $input > results_CR65.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output66.out -c 1 0 0 1 0 $input > results_CR66.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output67.out -c 1 0 0 2 0 $input > results_CR67.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output68.out -c 1 0 0 3 0 $input > results_CR68.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output69.out -c 1 0 1 0 0 $input > results_CR69.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output70.out -c 1 0 1 1 0 $input > results_CR70.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output71.out -c 1 0 1 2 0 $input > results_CR71.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output72.out -c 1 0 1 3 0 $input > results_CR72.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output73.out -c 1 0 2 0 0 $input > results_CR73.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output74.out -c 1 0 2 1 0 $input > results_CR74.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output75.out -c 1 0 2 2 0 $input > results_CR75.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output76.out -c 1 0 2 3 0 $input > results_CR76.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output77.out -c 1 0 3 0 0 $input > results_CR77.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output78.out -c 1 0 3 1 0 $input > results_CR78.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output79.out -c 1 0 3 2 0 $input > results_CR79.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output80.out -c 1 0 3 3 0 $input > results_CR80.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output81.out -c 1 1 0 0 0 $input > results_CR81.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output82.out -c 1 1 0 1 0 $input > results_CR82.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output83.out -c 1 1 0 2 0 $input > results_CR83.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output84.out -c 1 1 0 3 0 $input > results_CR84.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output85.out -c 1 1 1 0 0 $input > results_CR85.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output86.out -c 1 1 1 1 0 $input > results_CR86.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output87.out -c 1 1 1 2 0 $input > results_CR87.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output88.out -c 1 1 1 3 0 $input > results_CR88.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output89.out -c 1 1 2 0 0 $input > results_CR89.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output90.out -c 1 1 2 1 0 $input > results_CR90.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output91.out -c 1 1 2 2 0 $input > results_CR91.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output92.out -c 1 1 2 3 0 $input > results_CR92.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output93.out -c 1 1 3 0 0 $input > results_CR93.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output94.out -c 1 1 3 1 0 $input > results_CR94.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output95.out -c 1 1 3 2 0 $input > results_CR95.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output96.out -c 1 1 3 3 0 $input > results_CR96.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output97.out -c 1 2 0 0 0 $input > results_CR97.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output98.out -c 1 2 0 1 0 $input > results_CR98.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output99.out -c 1 2 0 2 0 $input > results_CR99.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output100.out -c 1 2 0 3 0 $input > results_CR100.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output101.out -c 1 2 1 0 0 $input > results_CR101.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output102.out -c 1 2 1 1 0 $input > results_CR102.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output103.out -c 1 2 1 2 0 $input > results_CR103.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output104.out -c 1 2 1 3 0 $input > results_CR104.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output105.out -c 1 2 2 0 0 $input > results_CR105.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output106.out -c 1 2 2 1 0 $input > results_CR106.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output107.out -c 1 2 2 2 0 $input > results_CR107.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output108.out -c 1 2 2 3 0 $input > results_CR108.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output109.out -c 1 2 3 0 0 $input > results_CR109.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output110.out -c 1 2 3 1 0 $input > results_CR110.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output111.out -c 1 2 3 2 0 $input > results_CR111.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output112.out -c 1 2 3 3 0 $input > results_CR112.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output113.out -c 1 3 0 0 0 $input > results_CR113.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output114.out -c 1 3 0 1 0 $input > results_CR114.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output115.out -c 1 3 0 2 0 $input > results_CR115.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output116.out -c 1 3 0 3 0 $input > results_CR116.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output117.out -c 1 3 1 0 0 $input > results_CR117.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output118.out -c 1 3 1 1 0 $input > results_CR118.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output119.out -c 1 3 1 2 0 $input > results_CR119.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output120.out -c 1 3 1 3 0 $input > results_CR120.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output121.out -c 1 3 2 0 0 $input > results_CR121.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output122.out -c 1 3 2 1 0 $input > results_CR122.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output123.out -c 1 3 2 2 0 $input > results_CR123.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output124.out -c 1 3 2 3 0 $input > results_CR124.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output125.out -c 1 3 3 0 0 $input > results_CR125.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output126.out -c 1 3 3 1 0 $input > results_CR126.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output127.out -c 1 3 3 2 0 $input > results_CR127.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output128.out -c 1 3 3 3 0 $input > results_CR128.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output129.out -c 2 0 0 0 0 $input > results_CR129.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output130.out -c 2 0 0 1 0 $input > results_CR130.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output131.out -c 2 0 0 2 0 $input > results_CR131.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output132.out -c 2 0 0 3 0 $input > results_CR132.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output133.out -c 2 0 1 0 0 $input > results_CR133.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output134.out -c 2 0 1 1 0 $input > results_CR134.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output135.out -c 2 0 1 2 0 $input > results_CR135.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output136.out -c 2 0 1 3 0 $input > results_CR136.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output137.out -c 2 0 2 0 0 $input > results_CR137.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output138.out -c 2 0 2 1 0 $input > results_CR138.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output139.out -c 2 0 2 2 0 $input > results_CR139.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output140.out -c 2 0 2 3 0 $input > results_CR140.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output141.out -c 2 0 3 0 0 $input > results_CR141.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output142.out -c 2 0 3 1 0 $input > results_CR142.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output143.out -c 2 0 3 2 0 $input > results_CR143.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output144.out -c 2 0 3 3 0 $input > results_CR144.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output145.out -c 2 1 0 0 0 $input > results_CR145.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output146.out -c 2 1 0 1 0 $input > results_CR146.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output147.out -c 2 1 0 2 0 $input > results_CR147.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output148.out -c 2 1 0 3 0 $input > results_CR148.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output149.out -c 2 1 1 0 0 $input > results_CR149.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output150.out -c 2 1 1 1 0 $input > results_CR150.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output151.out -c 2 1 1 2 0 $input > results_CR151.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output152.out -c 2 1 1 3 0 $input > results_CR152.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output153.out -c 2 1 2 0 0 $input > results_CR153.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output154.out -c 2 1 2 1 0 $input > results_CR154.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output155.out -c 2 1 2 2 0 $input > results_CR155.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output156.out -c 2 1 2 3 0 $input > results_CR156.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output157.out -c 2 1 3 0 0 $input > results_CR157.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output158.out -c 2 1 3 1 0 $input > results_CR158.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output159.out -c 2 1 3 2 0 $input > results_CR159.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output160.out -c 2 1 3 3 0 $input > results_CR160.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output161.out -c 2 2 0 0 0 $input > results_CR161.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output162.out -c 2 2 0 1 0 $input > results_CR162.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output163.out -c 2 2 0 2 0 $input > results_CR163.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output164.out -c 2 2 0 3 0 $input > results_CR164.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output165.out -c 2 2 1 0 0 $input > results_CR165.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output166.out -c 2 2 1 1 0 $input > results_CR166.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output167.out -c 2 2 1 2 0 $input > results_CR167.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output168.out -c 2 2 1 3 0 $input > results_CR168.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output169.out -c 2 2 2 0 0 $input > results_CR169.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output170.out -c 2 2 2 1 0 $input > results_CR170.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output171.out -c 2 2 2 2 0 $input > results_CR171.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output172.out -c 2 2 2 3 0 $input > results_CR172.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output173.out -c 2 2 3 0 0 $input > results_CR173.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output174.out -c 2 2 3 1 0 $input > results_CR174.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output175.out -c 2 2 3 2 0 $input > results_CR175.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output176.out -c 2 2 3 3 0 $input > results_CR176.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output177.out -c 2 3 0 0 0 $input > results_CR177.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output178.out -c 2 3 0 1 0 $input > results_CR178.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output179.out -c 2 3 0 2 0 $input > results_CR179.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output180.out -c 2 3 0 3 0 $input > results_CR180.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output181.out -c 2 3 1 0 0 $input > results_CR181.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output182.out -c 2 3 1 1 0 $input > results_CR182.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output183.out -c 2 3 1 2 0 $input > results_CR183.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output184.out -c 2 3 1 3 0 $input > results_CR184.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output185.out -c 2 3 2 0 0 $input > results_CR185.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output186.out -c 2 3 2 1 0 $input > results_CR186.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output187.out -c 2 3 2 2 0 $input > results_CR187.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output188.out -c 2 3 2 3 0 $input > results_CR188.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output189.out -c 2 3 3 0 0 $input > results_CR189.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output190.out -c 2 3 3 1 0 $input > results_CR190.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output191.out -c 2 3 3 2 0 $input > results_CR191.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output192.out -c 2 3 3 3 0 $input > results_CR192.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output193.out -c 3 0 0 0 0 $input > results_CR193.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output194.out -c 3 0 0 1 0 $input > results_CR194.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output195.out -c 3 0 0 2 0 $input > results_CR195.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output196.out -c 3 0 0 3 0 $input > results_CR196.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output197.out -c 3 0 1 0 0 $input > results_CR197.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output198.out -c 3 0 1 1 0 $input > results_CR198.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output199.out -c 3 0 1 2 0 $input > results_CR199.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output200.out -c 3 0 1 3 0 $input > results_CR200.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output201.out -c 3 0 2 0 0 $input > results_CR201.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output202.out -c 3 0 2 1 0 $input > results_CR202.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output203.out -c 3 0 2 2 0 $input > results_CR203.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output204.out -c 3 0 2 3 0 $input > results_CR204.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output205.out -c 3 0 3 0 0 $input > results_CR205.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output206.out -c 3 0 3 1 0 $input > results_CR206.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output207.out -c 3 0 3 2 0 $input > results_CR207.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output208.out -c 3 0 3 3 0 $input > results_CR208.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output209.out -c 3 1 0 0 0 $input > results_CR209.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output210.out -c 3 1 0 1 0 $input > results_CR210.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output211.out -c 3 1 0 2 0 $input > results_CR211.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output212.out -c 3 1 0 3 0 $input > results_CR212.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output213.out -c 3 1 1 0 0 $input > results_CR213.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output214.out -c 3 1 1 1 0 $input > results_CR214.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output215.out -c 3 1 1 2 0 $input > results_CR215.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output216.out -c 3 1 1 3 0 $input > results_CR216.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output217.out -c 3 1 2 0 0 $input > results_CR217.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output218.out -c 3 1 2 1 0 $input > results_CR218.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output219.out -c 3 1 2 2 0 $input > results_CR219.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output220.out -c 3 1 2 3 0 $input > results_CR220.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output221.out -c 3 1 3 0 0 $input > results_CR221.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output222.out -c 3 1 3 1 0 $input > results_CR222.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output223.out -c 3 1 3 2 0 $input > results_CR223.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output224.out -c 3 1 3 3 0 $input > results_CR224.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output225.out -c 3 2 0 0 0 $input > results_CR225.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output226.out -c 3 2 0 1 0 $input > results_CR226.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output227.out -c 3 2 0 2 0 $input > results_CR227.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output228.out -c 3 2 0 3 0 $input > results_CR228.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output229.out -c 3 2 1 0 0 $input > results_CR229.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output230.out -c 3 2 1 1 0 $input > results_CR230.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output231.out -c 3 2 1 2 0 $input > results_CR231.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output232.out -c 3 2 1 3 0 $input > results_CR232.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output233.out -c 3 2 2 0 0 $input > results_CR233.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output234.out -c 3 2 2 1 0 $input > results_CR234.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output235.out -c 3 2 2 2 0 $input > results_CR235.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output236.out -c 3 2 2 3 0 $input > results_CR236.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output237.out -c 3 2 3 0 0 $input > results_CR237.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output238.out -c 3 2 3 1 0 $input > results_CR238.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output239.out -c 3 2 3 2 0 $input > results_CR239.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output240.out -c 3 2 3 3 0 $input > results_CR240.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output241.out -c 3 3 0 0 0 $input > results_CR241.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output242.out -c 3 3 0 1 0 $input > results_CR242.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output243.out -c 3 3 0 2 0 $input > results_CR243.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output244.out -c 3 3 0 3 0 $input > results_CR244.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output245.out -c 3 3 1 0 0 $input > results_CR245.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output246.out -c 3 3 1 1 0 $input > results_CR246.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output247.out -c 3 3 1 2 0 $input > results_CR247.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output248.out -c 3 3 1 3 0 $input > results_CR248.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output249.out -c 3 3 2 0 0 $input > results_CR249.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output250.out -c 3 3 2 1 0 $input > results_CR250.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output251.out -c 3 3 2 2 0 $input > results_CR251.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output252.out -c 3 3 2 3 0 $input > results_CR252.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output253.out -c 3 3 3 0 0 $input > results_CR253.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output254.out -c 3 3 3 1 0 $input > results_CR254.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output255.out -c 3 3 3 2 0 $input > results_CR255.txt
java -cp /Applications/Jane.app/Contents/Java/Jane.jar edu.hmc.jane.CLI -o output256.out -c 3 3 3 3 0 $input > results_CR256.txt
